### ISSUE TITLE
Problem with Chrome v128

### ISSUE THREAD

**Issue by bradvf** [rstudio/chromote#170] opened 2024-08-23 15:51 UTC
Having errors after Chrome update to v128, for example:

When Chrome is already running on the machine, `b <- ChromoteSession$new()` produces the following error:

Error in `with_random_port()`:
! Cannot find an available port. Please try again.
Caused by error in `startup()`:
! Failed to start chrome. Error:

When Chrome is not already running `b <- ChromoteSession$new()` will run, but executing `b$view()` will not open any window.  Trying to open Chrome app will also not run after creating a new session with this command.

**Comment by gadenbuie** [comment] 2024-08-23 18:46
I just updated to Chrome 128.0.6613.85 and chromote is working fine for me. That's usually a sign that there are some environment or operating system characteristic at play with your issue. Can you please include the results of `devtools::session_info()`?

**Comment by bradvf** [comment] 2024-08-23 18:53
setting  value
 version  R version 4.3.0 (2023-04-21 ucrt)
 os       Windows 10 x64 (build 19045)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.utf8
 ctype    English_United States.utf8
 tz       America/Chicago
 date     2024-08-23
 rstudio  2023.06.2+561 Mountain Hydrangea (desktop)
 pandoc   3.1.1 @ C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)

**Comment by gadenbuie** [comment] 2024-08-23 21:03
@bradvf can you please include all of the output? If the output prints too many packages, try this `devtools::session_info(pkgs = "chromote")`.

**Comment by bradvf** [comment] 2024-08-23 21:50
@gadenbuie 
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.3.0 (2023-04-21 ucrt)
 os       Windows 10 x64 (build 19045)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.utf8
 ctype    English_United States.utf8
 tz       America/Chicago
 date     2024-08-23
 rstudio  2023.06.2+561 Mountain Hydrangea (desktop)
 pandoc   3.1.1 @ C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version  date (UTC) lib source
 AsioHeaders   1.22.1-2 2022-12-08 [1] CRAN (R 4.3.0)
 chromote    * 0.2.0    2024-02-12 [1] CRAN (R 4.3.3)
 cpp11         0.4.3    2022-10-12 [1] CRAN (R 4.3.0)
 curl          5.0.0    2023-01-12 [1] CRAN (R 4.3.0)
 fastmap       1.1.1    2023-02-24 [1] CRAN (R 4.3.0)
 jsonlite    * 1.8.8    2023-12-04 [1] CRAN (R 4.3.2)
 later         1.3.1    2023-05-02 [1] CRAN (R 4.3.0)
 magrittr      2.0.3    2022-03-30 [1] CRAN (R 4.3.0)
 processx      3.8.2    2023-06-30 [1] CRAN (R 4.3.2)
 promises      1.2.0.1  2021-02-11 [1] CRAN (R 4.3.0)
 ps            1.7.5    2023-04-18 [1] CRAN (R 4.3.0)
 R6            2.5.1    2021-08-19 [1] CRAN (R 4.3.0)
 Rcpp          1.0.10   2023-01-22 [1] CRAN (R 4.3.0)
 rlang         1.1.1    2023-04-28 [1] CRAN (R 4.3.0)
 websocket     1.4.1    2021-08-18 [1] CRAN (R 4.3.1)

**Comment by kumarnishanthtr** [comment] 2024-08-24 15:14
Having the issue since yesterday after chrome update to 128

```
> b <- ChromoteSession$new()
Error in launch_chrome(path, args) : Failed to start chrome. Error: 
```

**Comment by gadenbuie** [comment] 2024-08-24 15:37
Can you please try with the latest development version of chromote? At the very least it might surface more contextual about the error.

```r
remotes::install_github("rstudio/chromote")
```

**Comment by shafiul0304034** [comment] 2024-08-24 18:29
Very stressful situation since yesterday. Today me with my little team spent whole day to fix this issue but unable. We found out, the port number returned after execution with_random_port() function is always null.  I expect a help from a guru to find out where is the problem. Our hosted product in shinyapps.io for hotels room price analysis seems still working. However, problem is coming from desktop trial.

Cheers
Shafiul Islam || Founder of SaleForecast
 


> remotes::install_github("rstudio/chromote")
Downloading GitHub repo rstudio/chromote@HEAD
Running `R CMD build`...
* checking for file 'C:\Users\USER\AppData\Local\Temp\Rtmpe0PPHK\remotes114876f2531a\rstudio-chromote-f030285/DESCRIPTION' ... OK
* preparing 'chromote':
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building 'chromote_0.2.0.9000.tar.gz'
Installing package into ‘C:/Users/USER/AppData/Local/R/win-library/4.4’
(as ‘lib’ is unspecified)
* installing *source* package 'chromote' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (chromote)
> library(chromote)
> find_chrome()
[1] "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"
> ChromoteSession$new()
Error in `with_random_port()`:
! Cannot find an available port. Please try again.
Caused by error in `startup()`:
! Failed to start chrome. (No error messages were printed.)
Run `rlang::last_trace()` to see where the error occurred.

**Comment by bradvf** [comment] 2024-08-24 19:08
@gadenbuie same error with the development version: `Cannot find an available port. Please try again.`  Also tried updating all dependent packages.

**Comment by Migchw** [comment] 2024-08-25 14:33
Having the same issue here 

Error in with_random_port():
! Cannot find an available port. Please try again.
Caused by error in startup():
! Failed to start chrome. Error:

**Comment by bradvf** [comment] 2024-08-25 19:53
For anyone struggling with this, a temporary solution was to download [Chrome For Testing](https://developer.chrome.com/blog/chrome-for-testing) version 127 (https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.120/win64/chrome-win64.zip).  You can then point chromote to that browser via: 

```
chrome_path <- "C:\\Program Files\\ChromeForTesting\\chrome-win64-127\\chrome.exe"
m <- Chromote$new(browser = Chrome$new(path = chrome_path))
b <- m$new_session()
```

**Comment by gadenbuie** [comment] 2024-08-26 02:23
I was able to reproduce the issue with Chrome v128 in Windows 11 via Parallels. Immediately after installing the updated Chrome version, the following would fail as described above:

```r
library(chromote)
b <- ChromoteSession$new()
#> Error in `with_random_port()`:
#> ! Cannot find an available port. Please try again.
#> Caused by error in `startup()`:
#> ! Failed to start chrome. Error:
#> Run `rlang::last_trace()` to see where the error occurred.
```

The lack of error message is a result of the Chrome process exiting almost immediately, or before chromote has a chance to do anything with the process.

Running the following in a command prompt was exiting immediately without starting a Chrome process:

```
"C:\Program Files\Google\Chrome\Application\chrome.exe" --headless --remote-debugging-port=9876 --remote-allow-origins=http://127.0.0.1:9876
```

As I understand it, Chrome is in the process of transitioning from `--headless=old` to `--headless=new` ([described here](https://developer.chrome.com/docs/chromium/new-headless)):

> **Note:** Passing the `--headless` command-line flag without an explicit value still activates the old Headless mode, but we intend to change this default. We intend to remove the old Headless from the Chrome binary and stop supporting this mode in Puppeteer in 2024.

I couldn't find anything mentioning a change to the `--headless` flag in [Chrome's v128 release notes](https://developer.chrome.com/release-notes/128).

That said, when I changed `--headless` to `--headless=new` in the command prompt, headless chrome began working as expected. After running starting headless Chrome once with `--headless=new`, changing back to `--headless` started working again, too. At this point, starting a new Chrome session with chromote via `b <- ChromoteSession$new()` also started working as expected.

Can anyone in this thread try my process to see if it works for you? Use `find_chrome()` to find the path to Chrome on your machine

```r
chromote::find_chrome()
#> [1] "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"
```

and then, in a command or power shell prompt, run the executable once with the `--headless=new` flag.

```shell
"C:\Program Files\Google\Chrome\Application\chrome.exe" --headless=new --remote-debugging-port=9876
```

I included the `--remote-debugging-port` so that the process will print out a line like

```
DevTools listening on ws://127.0.0.1:9876/devtools/browser/d5ba3a11-3293-4482-a7ac-7e518acd2d5f
```

After that, you can stop the process by pressing Ctrl + C and then try using chromote in R to start a new session with

```
p <- ChromoteSession$new()
```

**Comment by bradvf** [comment] 2024-08-26 13:49
@gadenbuie I found that I can only run your command line when Chrome is closed.  When Chrome is already open, the command fails immediately.  However, I still receive the same errors in R after successfully running the command line.

**Comment by gadenbuie** [comment] 2024-08-26 13:57
@bradvf Does headless Chrome work correctly when called from the command line? Try running this command, it should output the HTML of https://example.com.

```shell
"C:\Program Files\Google\Chrome\Application\chrome.exe" --headless --dump-dom https://example.com
# <html><head>
#    <title>Example Domain</title>
# [...snip...]
# </body></html>
```

**Comment by gadenbuie** [comment] 2024-08-26 13:59
> When Chrome is already open, the command fails immediately. However, I still receive the same errors in R after successfully running the command line.

@bradvf Do you receive the same errors when Chrome is open or closed? You might need to use Task Manager to make verify that there aren't any running Chrome processes.

**Comment by bradvf** [comment] 2024-08-26 14:03
> @bradvf Does headless Chrome work correctly when called from the command line? Try running this command, it should output the HTML of https://example.com.
> 
> ```shell
> "C:\Program Files\Google\Chrome\Application\chrome.exe" --headless --dump-dom https://example.com
> # <html><head>
> #    <title>Example Domain</title>
> # [...snip...]
> # </body></html>
> ```

When Chrome is closed, this will work.  When Chrome is open, this produces no output. Guessing this is a problem directly with Chrome that chromote won't be able to get around.

**Comment by gadenbuie** [comment] 2024-08-26 14:03
oh! So the cause might be having or not having Chrome open, rather than the commands I was using. I stopped all chrome processes while testing `--headless=new` vs `--headless` so that I could correctly count the number of processes. But now I can reproduce the issue by opening and closing Chrome.

**Comment by gadenbuie** [comment] 2024-08-26 14:05
> When Chrome is closed, this will work. When Chrome is open, this produces no output. Guessing this is a problem directly with Chrome that chromote won't be able to get around.

That's right, this is certainly a Chrome-specific issue, especially since we can reproduce the error without using chromote at all. That's a good start! I'm surprised this hasn't been reported in other chrome-automation packages, though. 🤔

**Comment by gadenbuie** [comment] 2024-08-26 14:16
Also related: once I start a Chrome session via chromote, I can't then start a normal headful instance of Chrome until I completely shut down the R session.

**Comment by gadenbuie** [comment] 2024-08-26 14:27
Same behavior for Chrome Beta (129.0.6668.12 (arm64))

**Comment by gadenbuie** [comment] 2024-08-26 14:59
This has been reported in the Chromium bug tracker in at least two places, we'll have to wait for an upstream fix.

* [chrome headless mode is not working , non of the apis is working [361784547] - Chromium](https://issues.chromium.org/issues/361784547)
* [Shell-Scripts with --headless or --headless=new fail [361963983] - Chromium](https://issues.chromium.org/issues/361963983)

**Comment by shafiul0304034** [comment] 2024-08-26 17:58
> ```
> "C:\Program Files\Google\Chrome\Application\chrome.exe" --headless --remote-debugging-port=9876 --remote-allow-origins=http://127.0.0.1:9876
> ```

I have tried with this approach. However, it provides same error.
Error in `with_random_port()`:

**Comment by shafiul0304034** [comment] 2024-08-26 18:35
> For anyone struggling with this, a temporary solution was to download [Chrome For Testing](https://developer.chrome.com/blog/chrome-for-testing) version 127 (https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.120/win64/chrome-win64.zip). You can then point chromote to that browser via:
> 
> ```
> chrome_path <- "C:\\chrome-win64\\chrome.exe"
> m <- Chromote$new(browser = Chrome$new(path = chrome_path))
> b <- m$new_session()
> ```

Many thanks Bro. At least I have something now to work with.

**Comment by daviewales** [comment] 2024-08-27 23:20
Chromium is a snap on Ubuntu.
Some commands to get you back to a working version:

https://snapcraft.io/docs/quickstart-tour#pause-or-stop-automatic-updates
https://snapcraft.io/docs/quickstart-tour#revert-to-an-earlier-revision

**Comment by cderv** [comment] 2024-08-28 08:47
New chromium issue to follow 
- https://issues.chromium.org/issues/362545030

**Comment by gadenbuie** [comment] 2024-08-29 15:50
The dev version of chromote -- soon to be released to CRAN -- now uses `--headless=old` by default:

* #172

If you're encountering the problem in this thread, please use the latest version of chromote:

```r
remotes::install_github("rstudio/chromote")

# install.packages("chromote") # soon
```

`--headless=new` will end up being the default eventually, so please consider testing it in the future. You can use `options(chromote.headless = "new")` to try the new headless mode.

**Comment by Billy-Pilgrim-UIT** [comment] 2024-08-30 02:37
Hi - having big issues related to this chrome v128 update.

`> library(gt)
> 
> # Create a sample gt table
> gt_table <- gt(mtcars[1:5, ])
> 
> # Save the gt table to PNG using gtsave()
> gtsave(gt_table, "table.png")
Error in `with_random_port()`:
! Cannot find an available port. Please try again.
Caused by error in `Sys.getenv()`:
! wrong type for argument
Run `rlang::last_trace()` to see where the error occurred.`

Attempted the workaround suggested by bradvf and end up with same error:

`chrome_path <- "C:\\chrome-win64\\chrome.exe"
> m <- Chromote$new(browser = Chrome$new(path = chrome_path))
Error in `with_random_port()`:
! Cannot find an available port. Please try again.
Caused by error in `Sys.getenv()`:
! wrong type for argument
Run `rlang::last_trace()` to see where the error occurred.`

Any help appreciated - I am very reliant on this! Thankyou!

**Comment by tatvabodhini** [comment] 2024-08-30 11:04
I too encountered an error when the chrome got updgated. 

Right now I initiate the chrome session like this.. and I get the error 'Cannot find an available port. Please try again.'

chromote::set_default_chromote_object(
chromote::Chromote$new(chromote::Chrome$new(
args = c("--disable-gpu",
"--no-sandbox",
"--mute-audio",
"--disable-timeouts-for-profiling",
"--disable-dev-shm-usage",
c("--force-color-profile", "srgb"))
))
)

Is is suggested to add --headless=new ?? like below?

chromote::set_default_chromote_object(
chromote::Chromote$new(chromote::Chrome$new(
args = c("--disable-gpu",
"--no-sandbox",
"--mute-audio",
"--disable-timeouts-for-profiling",
"--disable-dev-shm-usage",
c("--force-color-profile", "srgb"),
c("--headless", "new")
)
))
)

**Comment by gadenbuie** [comment] 2024-08-30 11:07
@Billy-Pilgrim-UIT Can you please install the latest chromote (v0.3.1) and try again? There was a small but consequential bug in v0.3.0

**Comment by tatvabodhini** [comment] 2024-08-30 11:14
> @Billy-Pilgrim-UIT Can you please install the latest chromote (v0.3.1) and try again? There was a small but consequential bug in v0.3.0

do you recommend including c("--headless", "new") option? I would like to keep the old behaviour as is.

**Comment by tatvabodhini** [comment] 2024-08-30 11:37
@gadenbuie here is the full trace of the error when trying to iniate new chrome session. 

Error in fetching the screenshot of the URL:Cannot find an available port. Please try again.
Caused by error in `startup()`:
! Failed to start chrome. Error: mkdir: cannot create directory ‘/nonexistent’: Permission denied
touch: cannot touch '/nonexistent/.local/share/applications/mimeapps.list': No such file or directory
chrome_crashpad_handler: --database is required
Try 'chrome_crashpad_handler --help' for more information.
[114:114:0830/113516.429972:ERROR:socket.cc(120)] recvmsg: Connection reset by peer (104)

**Comment by gadenbuie** [comment] 2024-08-30 12:00
> do you recommend including c("--headless", "new") option? I would like to keep the old behaviour as is.

@tatvabodhini if you install the latest version of chromote, you won't need to change anything to keep the old behavior. With the latest version you can test the new headless mode by setting `options(chromote.headless = "new")`.

**Comment by ValentineHerr** [comment] 2024-08-30 14:20
The new version of chromote resolved my issue with saving to a png file (using `gt::gtsave`), thanks a lot!

But it has not solved my issue of converting an html to a pdf (using `pagedown::chrome_print`):

```
tab_1 <-
  gtcars |>
  dplyr::select(model, year, hp, trq) |>
  dplyr::slice(1:5) |>
  gt(rowname_col = "model") |>
  tab_stubhead(label = "car")

tab_1 |> gtsave(filename = "tab_1.html")
pagedown::chrome_print(input = "tab_1.html",
                       output = "tab_1.pdf")

```

This may be unrelated to the Chrome package, I need to investigate more...

**Comment by gadenbuie** [comment] 2024-08-30 14:52
@ValentineHerr Great to hear the new version of chromote is working for you! Unfortunately, while `pagedown` uses headless Chrome, it doesn't use chromote, so you'll have to wait for a pagedown-specific fix for `chrome_print()`.

**Comment by tatvabodhini** [comment] 2024-08-30 18:05
> > do you recommend including c("--headless", "new") option? I would like to keep the old behaviour as is.
> 
> @tatvabodhini if you install the latest version of chromote, you won't need to change anything to keep the old behavior. With the latest version you can test the new headless mode by setting `options(chromote.headless = "new")`.

@gadenbuie The issue still persisted. So I had to go back to old version of chrome. Chrome version "127.0.6533.119" worked for me with chromote 0.3.1 version package. I did not set the environment variables as refrerenced in package updates. I guess the old behaviour persisted and worked.

**Comment by gadenbuie** [comment] 2024-08-30 18:12
@tatvabodhini please feel free to open a new issue with a reproducible example

**Comment by Billy-Pilgrim-UIT** [comment] 2024-08-30 23:32
> @Billy-Pilgrim-UIT Can you please install the latest chromote (v0.3.1) and try again? There was a small but consequential bug in v0.3.0

Thankyou @gadenbuie  - that was my blind spot. I was running Chromote v0.3.0.

Upgrading to v0.3.1 appears to have fixed the issue. 
Thanks so much.

**Comment by NJKode** [comment] 2024-09-01 21:21
Adding this for posterity:

I was having issues with image sizes in Webshot. We have a Shiny app with Webshot image downloads that is deployed to shinyapps.io. After making a deploy to shinyapps.io on 23/08/24 (NZT), all images were getting downloaded with a width of 780px no matter what. After a lot of investigating (including finding this gh issue), I theorized that shinyapps.io had updated their server image to Chrome 128, and that our problems might also be caused by this version.

Just chiming in to say that updating to Chromote v0.3.1 (with no code updates) has fixed the issue! Images are now downloading at the correct size.

Thanks so much for this!

**Comment by wch** [comment] 2024-09-01 21:32
Closing because the problem is resolved with Chromote 0.3.1.

**Closed** 2024-09-01 21:31 UTC

**Comment by Migchw** [comment] 2024-09-02 03:48
I got error when try to update chromote package

package ‘chromote’ successfully unpacked and MD5 sums checked
Error in install.packages : ERROR: failed to lock directory ‘C:\Users\kaoakesu\AppData\Local\R\win-library\4.3’ for modifying
Try removing ‘C:\Users\kaoakesu\AppData\Local\R\win-library\4.3/00LOCK’

**Comment by Migchw** [comment] 2024-09-02 04:01
I can fix the problem with this code
options("install.lock"=FALSE)

thank so much !

> I got error when try to update chromote package
> 
> package ‘chromote’ successfully unpacked and MD5 sums checked Error in install.packages : ERROR: failed to lock directory ‘C:\Users\kaoakesu\AppData\Local\R\win-library\4.3’ for modifying Try removing ‘C:\Users\kaoakesu\AppData\Local\R\win-library\4.3/00LOCK’

**Comment by jobreu** [comment] 2025-11-14 17:06
I am encountering the same issue as in the original post:
```
Error in `with_random_port()`:
! Cannot find an available port. Please try again.
Caused by error in `startup()`:
! Failed to start chrome. Chrome is available on your system, so this error may be a configuration issue. Try `chromote_info()` to check and verify your settings. No error messages were logged.
```
I am using Win11, R 4.5.1, chromote 0.5.1, and Chrome 142.0.7444.163. The output of `chromote::chromote_info()` is:
```
---- {chromote} ----
   System: x86_64-w64-mingw32
R version: R version 4.5.1 (2025-06-13 ucrt)
 chromote: 0.5.1

---- Chrome ----
   Path: C:\Program Files\Google\Chrome\Application\chrome.exe
Version: 142.0.7444.163
   Args: --headless --disable-gpu --force-color-profile=srgb --disable-extensions --mute-audio
```

**Comment by gadenbuie** [comment] 2025-11-14 19:58
@jobreu please open a new issue. You're getting a similar error message but you're using Chrome v142, not Chrome v128.
