### ISSUE TITLE
Cannot launch chromote session from behind firewall

### ISSUE THREAD

**Issue by lodderig** [rstudio/chromote#87] opened 2022-05-04 13:48 UTC
When I launch

chromote::ChromoteSession$new()

in Rstudio on  Windows 10

I get the following error

Error in open.connection(con, "rb") : 
  Failed to connect to proxyzscaler.xxx port 1080: Connection refused

**Comment by hadley** [comment] 2024-01-30 19:17
Likely a duplicate of #106

**Closed by hadley** 2024-01-30 19:17 UTC
