### ISSUE TITLE
Chromote: timed out waiting for response to command Runtime.evaluate

### ISSUE THREAD

**Issue by saleforecast1** [rstudio/chromote#148] opened 2024-02-20 07:36 UTC
After 3-4 minutes, I encounter an error when using the chromote package on shinyapps.io.

2024-02-20T07:09:54.329205+00:00 shinyapps[11193889]: Warning: **Error in : Chromote: timed out waiting for response to command Runtime.evaluate**
2024-02-20T07:09:54.334345+00:00 shinyapps[11193889]:   [No stack trace available]
2024-02-20T07:09:54.339393+00:00 shinyapps[11193889]: From earlier call:
2024-02-20T07:09:54.345122+00:00 shinyapps[11193889]:   15: <Anonymous>
2024-02-20T07:09:54.350193+00:00 shinyapps[11193889]:   13: fn
2024-02-20T07:09:54.355138+00:00 shinyapps[11193889]:    8: retry
2024-02-20T07:09:54.359999+00:00 shinyapps[11193889]:    7: connect$retryingStartServer
2024-02-20T07:09:54.364792+00:00 shinyapps[11193889]:    6: eval
2024-02-20T07:09:54.369868+00:00 shinyapps[11193889]:    5: eval
2024-02-20T07:09:54.377205+00:00 shinyapps[11193889]:    4: eval
2024-02-20T07:09:54.382227+00:00 shinyapps[11193889]:    3: eval
2024-02-20T07:09:54.386992+00:00 shinyapps[11193889]:    2: eval.parent
2024-02-20T07:09:54.392106+00:00 shinyapps[11193889]:    1: local

**Comment by gadenbuie** [comment] 2024-02-20 14:04
Hi @saleforecast1, which version of chromote are you using? Is this a new error with code that previously worked with chromote 0.1.2? How does your app use chromote? Do you think you could create [a small, reproducible example](https://community.rstudio.com/t/shiny-debugging-and-reprex-guide/10001)?

**Comment by alex-silverman** [comment] 2024-08-09 21:26
Getting this same error. Originally, we noticed when trying to run shinytest2, which was working until a couple hours ago, but then started producing this error. The only thing that changed in between was that the server was restarted with additional memory and cpu. 

I can reproduce the issue now simply by entering the following into the R console:
`b <-ChromoteSession$new()`

Version of Chromote: 0.2.0
Meets all dependency requirements.
Some other OS info:
![image](https://github.com/user-attachments/assets/297d51f5-3613-4d33-98dd-9eab636896f4)

**Comment by jj-9** [comment] 2024-08-27 08:11
Hi all,

having a very similar problem here, but it only happens when using the targetId parameter.
Also, if it can help, it seems to happen on linux but not windows box.

Regards
JJ

**Comment by jj-9** [comment] 2024-09-12 06:19
Hello again,

this message to add that this error occurs since update to latest edge version (128 (ubuntu)).
With a version number 126, the problem does not occur.

Regards
JJ

**Comment by eliocamp** [comment] 2024-09-20 06:24
Hi, I can reproduce this error using the latest chromote from github. My chrome version is "Version 129.0.6668.58 (Official Build) (64-bit)"  on Ubuntu 22.04. 

``` r
b <- chromote::ChromoteSession$new()
#> Error: Chromote: timed out waiting for response to command Runtime.evaluate
```

<sup>Created on 2024-09-20 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.4.1 (2024-06-14)
#>  os       Ubuntu 22.04.5 LTS
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language en_AU:en
#>  collate  en_AU.UTF-8
#>  ctype    en_AU.UTF-8
#>  tz       Australia/Melbourne
#>  date     2024-09-20
#>  pandoc   3.1.11 @ /usr/lib/rstudio/resources/app/bin/quarto/bin/tools/x86_64/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  chromote      0.3.1   2024-09-20 [1] Github (rstudio/chromote@00c3509)
#>  cli           3.6.3   2024-06-21 [1] RSPM (R 4.4.0)
#>  digest        0.6.36  2024-06-23 [1] RSPM (R 4.4.0)
#>  evaluate      0.24.0  2024-06-10 [1] RSPM (R 4.4.0)
#>  fastmap       1.2.0   2024-05-15 [1] RSPM (R 4.4.0)
#>  fs            1.6.4   2024-04-25 [1] RSPM
#>  glue          1.7.0   2024-01-09 [1] RSPM
#>  htmltools     0.5.8.1 2024-04-04 [1] RSPM
#>  jsonlite      1.8.8   2023-12-04 [1] RSPM
#>  knitr         1.48    2024-07-07 [1] RSPM (R 4.4.0)
#>  later         1.3.2   2023-12-06 [1] RSPM
#>  lifecycle     1.0.4   2023-11-07 [1] RSPM
#>  magrittr      2.0.3   2022-03-30 [1] RSPM
#>  processx      3.8.4   2024-03-16 [1] RSPM
#>  promises      1.3.0   2024-04-05 [1] RSPM
#>  ps            1.7.7   2024-07-02 [1] RSPM (R 4.4.0)
#>  R6            2.5.1   2021-08-19 [1] RSPM
#>  Rcpp          1.0.13  2024-07-17 [1] RSPM (R 4.4.0)
#>  reprex        2.1.1   2024-07-06 [1] RSPM (R 4.4.0)
#>  rlang         1.1.4   2024-06-04 [1] RSPM (R 4.4.0)
#>  rmarkdown     2.27    2024-05-17 [1] RSPM (R 4.4.0)
#>  rstudioapi    0.16.0  2024-03-24 [1] RSPM
#>  sessioninfo   1.2.2   2021-12-06 [1] RSPM
#>  websocket     1.4.2   2024-07-22 [1] RSPM
#>  withr         3.0.0   2024-01-16 [1] RSPM
#>  xfun          0.46    2024-07-18 [1] RSPM (R 4.4.0)
#>  yaml          2.3.9   2024-07-05 [1] RSPM (R 4.4.0)
#> 
#>  [1] /home/user1/R/x86_64-pc-linux-gnu-library/4.4
#>  [2] /opt/R/4.4.1/lib/R/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by jj-9** [comment] 2024-10-03 07:06
Hello,

I confirm @eliocamp trouble here with version 129.0.2792.65 on ubuntu 24.04

Regards
JJ

**Comment by gadenbuie** [comment] 2024-10-03 14:50
Can you try running this code in a new session (and share the output here)>

```r
library(chromote)
system(paste(find_chrome(), "--version"))
b <- ChromoteSession$new()

dir(tempdir(), pattern = "chrome-", full.names = TRUE) |>
  setNames(nm = _) |>
  purrr::map(brio::read_file) |>
  purrr::iwalk(\(x, file) cat("\n---- ", file, " ----\n", x, sep = ""))
```

**Comment by eliocamp** [comment] 2024-10-04 00:09
``` r
library(chromote)
system(paste(find_chrome(), "--version"), intern = TRUE)
#> [1] "Google Chrome 129.0.6668.89 "
b <- ChromoteSession$new()

dir(tempdir(), pattern = "chrome-", full.names = TRUE) |>
  setNames(nm = _) |>
  purrr::map(brio::read_file) |>
  purrr::iwalk(\(x, file) cat("\n---- ", file, " ----\n", x, sep = ""))
#> 
#> ---- /tmp/RtmpId45k0/chrome-stderr-dc906d7398a4.log ----
#> Old Headless mode will be removed from the Chrome binary soon. Please use the new Headless mode (https://developer.chrome.com/docs/chromium/new-headless) or the chrome-headless-shell which is a standalone implementation of the old Headless mode (https://developer.chrome.com/blog/chrome-headless-shell).
#> 
#> 
#> DevTools listening on ws://127.0.0.1:40821/devtools/browser/a4938512-e4c5-4e71-b52a-5e482532b2ed
#> [1004/100851.860410:WARNING:sandbox_linux.cc(430)] InitializeSandbox() called with multiple threads in process gpu-process.
#> [1004/100851.861918:WARNING:viz_main_impl.cc(85)] VizNullHypothesis is disabled (not a warning)
#> 
#> ---- /tmp/RtmpId45k0/chrome-stdout-dc905e7dfbf3.log ----
```

<sup>Created on 2024-10-04 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by alex-silverman** [comment] 2024-10-04 00:11
Our issue was a throttling one.  We removed throttling from our servers and
that fixed the issue

**Comment by jj-9** [comment] 2024-10-04 14:06
Hi !

not really sure to understand the correction, but works good back again here.

Thanks
JJ

**Comment by gadenbuie** [comment] 2024-10-04 20:59
Thanks everyone, it sounds like this issue has resolved on its own (scary but I'll take it). I'm going to close this thread but please feel free to comment if you run into this again (be sure to include the output from the code listed above).

**Closed by gadenbuie** 2024-10-04 20:59 UTC

**Comment by collioud** [comment] 2025-03-25 10:17
Hello,

Got also this issue with the new 0.5 version trying to use Vivaldi browser...
Best regards,
Arnaud

```
> Sys.setenv(CHROMOTE_CHROME = "/usr/bin/vivaldi")
> library(chromote)
> system(paste(find_chrome(), "--version"))
Vivaldi 7.2.3621.67 stable
> b <- ChromoteSession$new()
Erreur : Chromote: timed out waiting for response to command Runtime.evaluate
```

My config:
```
> sessionInfo()
R version 4.4.3 (2025-02-28)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 24.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.12.0 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.12.0

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8       
 [4] LC_COLLATE=fr_FR.UTF-8     LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8   
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Paris

tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] chromote_0.5.0

loaded via a namespace (and not attached):
 [1] websocket_1.4.2   processx_3.8.6    compiler_4.4.3    fastmap_1.2.0    
 [5] magrittr_2.0.3    R6_2.6.1          cli_3.6.4         promises_1.3.2   
 [9] later_1.4.1       tools_4.4.3       rstudioapi_0.17.1 Rcpp_1.0.14      
[13] jsonlite_1.9.1    ps_1.9.0          rlang_1.1.5    
```

**Comment by gadenbuie** [comment] 2025-03-25 13:17
Hi @collioud, I moved your comment to a new issue, #222
